package com.hafu.Hafu.domain;
// Generated 2017-8-10 10:33:21 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HafuUserComment generated by hbm2java
 */
public class HafuUserComment implements java.io.Serializable {

	private Integer uid;
	private String username;
	private String password;
	private Date regtime;
	private String regphone;
	private int mainAddress;
	private String icon;
	private Set hafuCheckoutComments = new HashSet(0);
	private Set hafuUserProfileComments = new HashSet(0);

	public HafuUserComment() {
	}

	public HafuUserComment(Date regtime, String regphone, int mainAddress) {
		this.regtime = regtime;
		this.regphone = regphone;
		this.mainAddress = mainAddress;
	}

	public HafuUserComment(String username, String password, Date regtime, String regphone, int mainAddress,
			String icon, Set hafuCheckoutComments, Set hafuUserProfileComments) {
		this.username = username;
		this.password = password;
		this.regtime = regtime;
		this.regphone = regphone;
		this.mainAddress = mainAddress;
		this.icon = icon;
		this.hafuCheckoutComments = hafuCheckoutComments;
		this.hafuUserProfileComments = hafuUserProfileComments;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegtime() {
		return this.regtime;
	}

	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	public String getRegphone() {
		return this.regphone;
	}

	public void setRegphone(String regphone) {
		this.regphone = regphone;
	}

	public int getMainAddress() {
		return this.mainAddress;
	}

	public void setMainAddress(int mainAddress) {
		this.mainAddress = mainAddress;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Set getHafuCheckoutComments() {
		return this.hafuCheckoutComments;
	}

	public void setHafuCheckoutComments(Set hafuCheckoutComments) {
		this.hafuCheckoutComments = hafuCheckoutComments;
	}

	public Set getHafuUserProfileComments() {
		return this.hafuUserProfileComments;
	}

	public void setHafuUserProfileComments(Set hafuUserProfileComments) {
		this.hafuUserProfileComments = hafuUserProfileComments;
	}

}
